### ISSUE TITLE
uBlock compatibility

### ISSUE THREAD

**Issue by IDKwhattoputhere** [magdev/leistungsschutzgelderpresser#8]
What format exactly is this blacklist? I wanted to add it to uBlock Origin but the formatting isn't compatible. uBO only supports:
- ABP-style filer lists (e.g. https://easylist-downloads.adblockplus.org/adwarefilters.txt)
- hosts files (e.g. https://adaway.org/hosts.txt)
- Simple domain lists (e.g. https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt)

**Comment by IDKwhattoputhere** [comment]
Never mind. https://github.com/IDKwhattoputhere/leistungsschutzgelderpresser/blob/master/domains.txt

**Comment by magdev** [comment]
Glad to hear the list will make it into uBO. :)
